name: qiu_shi_bai_ke
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.2
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^0.5.2
  url_launcher: ^5.0.2
  flutter_easyrefresh: ^1.2.7
  provide: ^1.0.2
  fluttertoast: ^3.0.4
  fluro: ^1.4.0
  flutter_html: ^0.9.6
  shared_preferences: ^0.5.2
  chewie: ^0.9.7
  transparent_image: ^1.0.0
  video_player: ^0.10.1
  flutter_ijkplayer: ^0.2.4
  webview_flutter: ^0.3.7+1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icon_chat@3x.png
    - images/icon_chat_active@3x.png
    - images/icon_main@3x.png
    - images/icon_main_active@3x.png
    - images/icon_me@3x.png
    - images/icon_me_active@3x.png
    - images/main_tab_live@3x.png
    - images/main_tab_live_active@3x.png
    - images/main_tab_qbfriends@3x.png
    - images/main_tab_qbfriends_active@3x.png
    - images/qbf_sign_in@3x.png
    - images/home_search_icon@3x.png
    - images/icon_post_new@3x.png
    - images/hot@3x.png
    - images/adfree_close@3x.png
    - images/qbf_sign_shit_empty@3x.png
    - images/button_comment@3x.png
    - images/icon_my_article_more@3x.png
    - images/icon_against_active@3x.png
    - images/icon_against_immersive@3x.png
    - images/icon_for_active@3x.png
    - images/icon_for_immersive@3x.png
    - images/btn_focus_immersive@3x.png
    - images/video_pause@3x.png
    - images/video_play@3x.png
    - images/comment_loading_empty_shit@3x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
